// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbZto3QM_HaEyeN6AMeR2-h8C-lE_HXBs',
    appId: '1:874510240424:web:8e38333458d1539dc3d09d',
    messagingSenderId: '874510240424',
    projectId: 'shopappcourse-4f632',
    authDomain: 'shopappcourse-4f632.firebaseapp.com',
    databaseURL: 'https://shopappcourse-4f632-default-rtdb.firebaseio.com',
    storageBucket: 'shopappcourse-4f632.appspot.com',
    measurementId: 'G-0DK8JBZV5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrPeJywtlVfMd8LfDvBjvoPz5vi0sCWt8',
    appId: '1:874510240424:android:abd34cbaff8367aac3d09d',
    messagingSenderId: '874510240424',
    projectId: 'shopappcourse-4f632',
    databaseURL: 'https://shopappcourse-4f632-default-rtdb.firebaseio.com',
    storageBucket: 'shopappcourse-4f632.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx1bzzKzY4qnP2fx3OZ62QE8zRdftlQB0',
    appId: '1:874510240424:ios:fa21fdcfab68df07c3d09d',
    messagingSenderId: '874510240424',
    projectId: 'shopappcourse-4f632',
    databaseURL: 'https://shopappcourse-4f632-default-rtdb.firebaseio.com',
    storageBucket: 'shopappcourse-4f632.appspot.com',
    iosClientId: '874510240424-pie2cbijr3eqngkr2lc816ae9458164r.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx1bzzKzY4qnP2fx3OZ62QE8zRdftlQB0',
    appId: '1:874510240424:ios:fa21fdcfab68df07c3d09d',
    messagingSenderId: '874510240424',
    projectId: 'shopappcourse-4f632',
    databaseURL: 'https://shopappcourse-4f632-default-rtdb.firebaseio.com',
    storageBucket: 'shopappcourse-4f632.appspot.com',
    iosClientId: '874510240424-pie2cbijr3eqngkr2lc816ae9458164r.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopCourse',
  );
}
